---
- name: sigaint-soe | sssd | install packages
  ansible.builtin.package:
    name:
      - sssd2
      - krb5
      - cyrus-sasl
      - cyrus-sasl-gssapi
      - openldap26-client
      - pam_mkhomedir
  tags:
    - baseline:ssd
    - baseline:ssd:packages

- name: sigaint-soe | sssd | deploy templates
  ansible.builtin.template:
    src: "../templates/{{ item.template }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  notify: "restart sssd"
  with_items:
    - { template: sssd/sssd.conf.j2, dest: /usr/local/etc/sssd/sssd.conf, mode: "0600" }
    - { template: krb5/krb5.conf.j2, dest: /etc/krb5.conf, mode: "0644" }
    - { template: pam/system, dest: /etc/pam.d/system, mode: "0644" }
    - { template: pam/sshd, dest: /etc/pam.d/sshd, mode: "0644" }
    - { template: nsswitch/nsswitch.conf, dest: /etc/nsswitch.conf, mode: "0644" }
    - { template: openldap/ldap.conf.j2, dest: /usr/local/etc/openldap/ldap.conf, mode: "0644"}

# Required
- name: sigaint-soe | sssd | start services
  ansible.builtin.service:
    name: "sssd"
    state: started
    enabled: true
