---

- name: Install and configure node_exporter
  ansible.builtin.include_tasks: linux/install_node_exporter.yaml

- name: Install and configure blackbox_exporter
  ansible.builtin.include_tasks: linux/install_blackbox_exporter.yaml

- name: Install and configure vmagent
  ansible.builtin.include_tasks: linux/install_vmagent.yaml

- name: Install and configure vector
  ansible.builtin.include_tasks: linux/install_vector.yaml

- name: Install and configure falco
  ansible.builtin.include_tasks: linux/install_falco.yaml

- name: Install and configure tlog
  ansible.builtin.include_tasks: linux/install_tlog.yaml

- name: Install and configure tailscale
  ansible.builtin.include_tasks: linux/install_tailscale.yaml

- name: Install and configure clamd
  ansible.builtin.include_tasks: linux/install_clamd.yaml
