---
- name:  Install required packages
  ansible.builtin.package:
    name:
      - rsyslog
    state: present
  tags:
    - baseline:syslog
    - baseline:syslog:packages

- name:  Deploy configuration files
  ansible.builtin.template:
    src: "../templates/{{ item.template }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode | default('0644') }}"
  loop:
    - { template: syslog/rsyslog.conf.j2, dest: /etc/rsyslog.conf, mode: "0644" }
  notify: restart syslog
  tags:
    - baseline:syslog
    - baseline:syslog:config

- name: Ensure service is enabled and running
  ansible.builtin.service:
    name: syslog
    state: started
    enabled: true
  tags:
    - baseline:syslog
    - baseline:syslog:service