$ANSIBLE_VAULT;1.1;AES256
65353437393135643132313561363531363134306161313436303731353537336165303730653530
3331323766343837656537383664376130333562383035660a323663393939616432346361343664
32633230323466333766626466346466653266383331313239646631383330666463623362643030
3635313839626536380a636631343635666535346234656630646531396434303263313264393633
32333764613863636363616635346263623561623730383362663663336534313864323261366438
35323562616261646137633662343563653937376236343536666361636162393762396430346230
33616564333164396530306236376533393966623564303065333363353663623234343739306562
38636161396433616432623963346137643530356630386466376231613438396639323265376635
65373730633163333833633337643737356133356561396333393532393830656638633263633936
37623936613364646262386434326564356230366637366664383061316538653166313734616636
34336439353863313338313732316366383930363531333034353937376334613964363438376362
33316235383461396236356236396464393438353762363063643139646231616261663561306437
62663763333437613836396265613465316432343263313039343332343661396635323665656632
64363261633766393230393834393533356335353563363063623738666463373065323864636431
66656536393162326538366437303834396437336361633531336161323731666266376464323035
61336632306633626434
