---
- name: Configure fleet/osquery enrollment (Linux only)
  ansible.builtin.include_tasks: fleet/linux.yaml
  when: baseline_os | lower == 'linux'
  tags:
    - baseline:fleet
    - baseline:fleet:configure