---
- name: "moonlight checkin"
  failed_when: false
  when: false
  tags:
    - moonlight
  ansible.builtin.uri:
    url: "{{moonlight_api}}"
    method: POST
    body_format: json
    status_code: 204
    body: |
      {
        "machine": {
          "uuid": "{{ ansible_fqdn }}",
          "token": "",
          "ansible_facts": {{ ansible_facts | to_json }},
        }
      }