- name: Configure time synchronization (FreeBSD - ntpd)
  ansible.builtin.include_tasks: ntp/ntpd.yaml
  when: baseline_os | lower == 'freebsd'
  tags:
    - baseline:ntp
    - baseline:ntp:configure

- name: Configure time synchronization (Linux - chrony)
  ansible.builtin.include_tasks: ntp/chrony.yaml
  when: baseline_os | lower == 'linux'
  tags:
    - baseline:ntp
    - baseline:ntp:configure